export const mockEngagements = [
  {
    id: "eng-001",
    title: "Q1 2026 Financial Controls Audit",
    department: "Finance",
    status: "FIELDWORK" as const,
    riskRating: "HIGH" as const,
    leadAuditor: "Sarah Chen",
    startDate: "2026-01-15",
    endDate: "2026-03-15",
    findingsCount: 4,
    progress: 65,
  },
  {
    id: "eng-002",
    title: "IT Security Compliance Review",
    department: "Information Technology",
    status: "PLANNING" as const,
    riskRating: "CRITICAL" as const,
    leadAuditor: "Marcus Johnson",
    startDate: "2026-02-01",
    endDate: "2026-04-30",
    findingsCount: 0,
    progress: 15,
  },
  {
    id: "eng-003",
    title: "Procurement Process Audit",
    department: "Operations",
    status: "REVIEW" as const,
    riskRating: "MEDIUM" as const,
    leadAuditor: "Emily Rodriguez",
    startDate: "2025-11-01",
    endDate: "2026-01-31",
    findingsCount: 7,
    progress: 85,
  },
  {
    id: "eng-004",
    title: "HR Payroll Compliance Audit",
    department: "Human Resources",
    status: "COMPLETED" as const,
    riskRating: "LOW" as const,
    leadAuditor: "David Kim",
    startDate: "2025-09-01",
    endDate: "2025-12-15",
    findingsCount: 2,
    progress: 100,
  },
  {
    id: "eng-005",
    title: "Vendor Risk Assessment",
    department: "Supply Chain",
    status: "REPORTING" as const,
    riskRating: "HIGH" as const,
    leadAuditor: "Sarah Chen",
    startDate: "2025-12-01",
    endDate: "2026-02-28",
    findingsCount: 5,
    progress: 90,
  },
];

export const mockFindings = [
  {
    id: "FND-001",
    title: "Segregation of duties violation in AP process",
    engagementTitle: "Q1 2026 Financial Controls Audit",
    status: "OPEN" as const,
    riskRating: "HIGH" as const,
    owner: "John Martinez",
    dueDate: "2026-03-01",
    originalDueDate: null as string | null,
    dueDateExtensionReason: null as string | null,
    dateIdentified: "2026-01-22",
  },
  {
    id: "FND-002",
    title: "Missing approval signatures on purchase orders over $50K",
    engagementTitle: "Procurement Process Audit",
    status: "IN_REMEDIATION" as const,
    riskRating: "CRITICAL" as const,
    owner: "Lisa Wang",
    dueDate: "2026-02-15",
    originalDueDate: "2026-01-15",
    dueDateExtensionReason: "Vendor system migration delayed implementation of new approval workflow",
    dateIdentified: "2025-12-10",
  },
  {
    id: "FND-003",
    title: "Outdated access control lists for financial systems",
    engagementTitle: "Q1 2026 Financial Controls Audit",
    status: "AWAITING_VALIDATION" as const,
    riskRating: "MEDIUM" as const,
    owner: "Tom Nguyen",
    dueDate: "2026-02-28",
    originalDueDate: null as string | null,
    dueDateExtensionReason: null as string | null,
    dateIdentified: "2026-01-18",
  },
  {
    id: "FND-004",
    title: "Incomplete vendor due diligence documentation",
    engagementTitle: "Vendor Risk Assessment",
    status: "OPEN" as const,
    riskRating: "HIGH" as const,
    owner: "Rachel Adams",
    dueDate: "2026-03-15",
    originalDueDate: "2026-02-15",
    dueDateExtensionReason: "Awaiting response from three key vendors on updated compliance questionnaires",
    dateIdentified: "2026-01-05",
  },
  {
    id: "FND-005",
    title: "Payroll exception report not reviewed monthly",
    engagementTitle: "HR Payroll Compliance Audit",
    status: "CLOSED" as const,
    riskRating: "LOW" as const,
    owner: "Kevin Brown",
    dueDate: "2025-11-30",
    originalDueDate: null as string | null,
    dueDateExtensionReason: null as string | null,
    dateIdentified: "2025-10-15",
  },
  {
    id: "FND-006",
    title: "No encryption at rest for sensitive vendor data",
    engagementTitle: "Vendor Risk Assessment",
    status: "OPEN" as const,
    riskRating: "CRITICAL" as const,
    owner: "Tom Nguyen",
    dueDate: "2026-02-20",
    originalDueDate: null as string | null,
    dueDateExtensionReason: null as string | null,
    dateIdentified: "2026-01-12",
  },
  {
    id: "FND-007",
    title: "Excessive admin privileges on ERP system",
    engagementTitle: "Q1 2026 Financial Controls Audit",
    status: "IN_REMEDIATION" as const,
    riskRating: "HIGH" as const,
    owner: "Lisa Wang",
    dueDate: "2026-03-10",
    originalDueDate: "2026-02-10",
    dueDateExtensionReason: "ERP vendor requires additional lead time for privilege restructuring in production",
    dateIdentified: "2026-01-25",
  },
];

export const dashboardStats = {
  activeEngagements: 3,
  openFindings: 4,
  criticalFindings: 2,
  completionRate: 72,
  overdueFindings: 1,
  findingsByRisk: { CRITICAL: 2, HIGH: 3, MEDIUM: 1, LOW: 1 },
  engagementsByStatus: {
    PLANNING: 1,
    FIELDWORK: 1,
    REVIEW: 1,
    REPORTING: 1,
    COMPLETED: 1,
  },
};
